import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import type { FastifyInstance } from 'fastify';
import { buildApp } from '../src/app';
import { loadConfig } from '../src/config/env';
import { createPool } from '../src/db/pool';
import { SalesFixture, expectStatus } from './salesTestSupport';

const databaseUrl = process.env.TEST_DATABASE_URL;
describe.skipIf(!databaseUrl)('v0.15 time tracking isolated integration', () => {
  let app: FastifyInstance; let pool: ReturnType<typeof createPool>; let fixture: SalesFixture; let auth:any; let employeeId:string; let entryId:string; let sheetId:string;
  beforeAll(async()=>{pool=createPool(databaseUrl!);app=await buildApp({config:loadConfig({NODE_ENV:'test',DATABASE_URL:databaseUrl!,DOCUMENT_STORAGE_DIR:'time-v15-test',LOG_LEVEL:'silent',EMAIL_DRIVER:'dev',EMAIL_DEV_OUTBOX:'true',TOTP_ENCRYPTION_KEY:'a'.repeat(64),COOKIE_SECURE:'false'}),db:pool});fixture=new SalesFixture(app,pool,`time15-${Date.now().toString(36)}`);auth=await fixture.setupOwner('Time Tracking QA');const e=await fixture.request({method:'POST',url:'/api/v1/employees',tenantId:auth.tenantId,cookie:auth.cookie,csrf:auth.csrf,body:{first_name:'Time',last_name:'Worker'}});expectStatus(e,201,'employee');employeeId=e.body.employee.id;const em=await fixture.request({method:'POST',url:`/api/v1/employees/${employeeId}/employments`,tenantId:auth.tenantId,cookie:auth.cookie,csrf:auth.csrf,body:{job_title:'Builder',start_date:'2026-01-10'}});expectStatus(em,201,'employment');});
  afterAll(async()=>{await app.close();await pool.end();});
  const req=(method:any,url:string,body?:any)=>fixture.request({method,url,body,tenantId:auth.tenantId,cookie:auth.cookie,csrf:auth.csrf});
  it('covers work, duration-only, absence, validation and CRUD',async()=>{let r=await req('POST','/api/v1/time-tracking/entries',{employee_id:employeeId,work_date:'2026-09-01',start_time:'2026-09-01T08:00:00+03:00',end_time:'2026-09-01T16:30:00+03:00',break_minutes:30});expectStatus(r,201,'work');expect(r.body.entry.duration_minutes).toBe(510);entryId=r.body.entry.id;r=await req('POST','/api/v1/time-tracking/entries',{employee_id:employeeId,work_date:'2026-09-02',duration_minutes:480,break_minutes:0});expectStatus(r,201,'duration');r=await req('POST','/api/v1/time-tracking/entries',{employee_id:employeeId,work_date:'2026-09-03',entry_kind:'ABSENCE',work_type:'SICK_LEAVE',duration_minutes:480,break_minutes:0});expectStatus(r,201,'absence');r=await req('POST','/api/v1/time-tracking/entries',{employee_id:employeeId,work_date:'2026-09-04',start_time:'2026-09-04T08:00:00+03:00',end_time:'2026-09-04T10:00:00+03:00',break_minutes:180});expectStatus(r,400,'break');r=await req('GET','/api/v1/time-tracking/entries');expectStatus(r,200,'list');expect(r.body.entries.length).toBe(3);r=await req('GET',`/api/v1/time-tracking/entries/${entryId}`);expectStatus(r,200,'detail');r=await req('PATCH',`/api/v1/time-tracking/entries/${entryId}`,{description:'updated'});expectStatus(r,200,'update');r=await req('DELETE',`/api/v1/time-tracking/entries/${entryId}`);expectStatus(r,200,'delete');});
  it('enforces employment dates and summarizes absence separately',async()=>{const r=await req('POST','/api/v1/time-tracking/entries',{employee_id:employeeId,work_date:'2026-01-09',duration_minutes:60,break_minutes:0});expectStatus(r,400,'employment date');const s=await req('GET','/api/v1/time-tracking/summary?from=2026-09-01&to=2026-09-30');expectStatus(s,200,'summary');expect(s.body.daily.some((x:any)=>Number(x.absence)>0)).toBe(true);});
  it('runs timesheet lifecycle to locked and rejects locked mutation',async()=>{let r=await req('POST','/api/v1/time-tracking/entries',{employee_id:employeeId,work_date:'2026-09-05',duration_minutes:60,break_minutes:0});expectStatus(r,201,'lock entry');const lockedEntry=r.body.entry.id;r=await req('POST','/api/v1/time-tracking/timesheets',{employee_id:employeeId,period_start:'2026-09-01',period_end:'2026-09-30'});expectStatus(r,201,'timesheet');sheetId=r.body.timesheet.id;r=await req('POST',`/api/v1/time-tracking/timesheets/${sheetId}/submit`,{});expectStatus(r,200,'submit');r=await req('POST',`/api/v1/time-tracking/timesheets/${sheetId}/approve`,{});expectStatus(r,200,'approve');r=await req('POST',`/api/v1/time-tracking/timesheets/${sheetId}/lock`,{});expectStatus(r,200,'lock');r=await req('PATCH',`/api/v1/time-tracking/entries/${lockedEntry}`,{description:'blocked'});expect(r.status).toBe(409);});
});
