exports.shorthands = undefined;
exports.up = (pgm) => {
  pgm.createTable('time_entries', {
    id:{type:'uuid',primaryKey:true,default:pgm.func('gen_random_uuid()')}, tenant_id:{type:'uuid',notNull:true,references:'tenants',onDelete:'CASCADE'}, employee_id:{type:'uuid',notNull:true}, employment_id:{type:'uuid'}, work_date:{type:'date',notNull:true}, start_time:{type:'timestamptz'}, end_time:{type:'timestamptz'}, duration_minutes:{type:'integer',notNull:true}, break_minutes:{type:'integer',notNull:true,default:0}, entry_kind:{type:'text',notNull:true,default:'WORK'}, work_type:{type:'text',notNull:true,default:'REGULAR'}, project_code:{type:'text'}, project_name:{type:'text'}, cost_center:{type:'text'}, work_location:{type:'text'}, description:{type:'text'}, source:{type:'text',notNull:true,default:'MANUAL'}, status:{type:'text',notNull:true,default:'DRAFT'}, created_by:{type:'uuid',notNull:true,references:'users'}, created_at:{type:'timestamptz',notNull:true,default:pgm.func('now()')},updated_at:{type:'timestamptz',notNull:true,default:pgm.func('now()')}
  });
  pgm.createTable('timesheets', { id:{type:'uuid',primaryKey:true,default:pgm.func('gen_random_uuid()')},tenant_id:{type:'uuid',notNull:true,references:'tenants',onDelete:'CASCADE'},employee_id:{type:'uuid',notNull:true},period_start:{type:'date',notNull:true},period_end:{type:'date',notNull:true},status:{type:'text',notNull:true,default:'DRAFT'},submitted_at:{type:'timestamptz'},submitted_by:{type:'uuid',references:'users'},approved_at:{type:'timestamptz'},approved_by:{type:'uuid',references:'users'},rejected_at:{type:'timestamptz'},rejection_reason:{type:'text'},locked_at:{type:'timestamptz'},created_at:{type:'timestamptz',notNull:true,default:pgm.func('now()')},updated_at:{type:'timestamptz',notNull:true,default:pgm.func('now()')} });
  pgm.createTable('timesheet_approval_history',{id:{type:'uuid',primaryKey:true,default:pgm.func('gen_random_uuid()')},tenant_id:{type:'uuid',notNull:true,references:'tenants',onDelete:'CASCADE'},timesheet_id:{type:'uuid',notNull:true},actor_id:{type:'uuid',notNull:true,references:'users'},action:{type:'text',notNull:true},reason:{type:'text'},created_at:{type:'timestamptz',notNull:true,default:pgm.func('now()')}});
  pgm.sql(`ALTER TABLE time_entries ADD CONSTRAINT time_entries_employee_fk FOREIGN KEY (tenant_id,employee_id) REFERENCES employees(tenant_id,id) ON DELETE RESTRICT, ADD CONSTRAINT time_entries_employment_fk FOREIGN KEY (employment_id) REFERENCES employments(id) ON DELETE RESTRICT, ADD CONSTRAINT time_entries_duration_check CHECK (duration_minutes >= 0), ADD CONSTRAINT time_entries_break_check CHECK (break_minutes >= 0 AND break_minutes <= duration_minutes), ADD CONSTRAINT time_entries_kind_check CHECK (entry_kind IN ('WORK','ABSENCE')), ADD CONSTRAINT time_entries_work_type_check CHECK (work_type IN ('REGULAR','OVERTIME','EVENING','NIGHT','SUNDAY','HOLIDAY_WORK','OTHER_WORK','SICK_LEAVE','ANNUAL_LEAVE','UNPAID_LEAVE','FAMILY_LEAVE','TRAINING','OTHER_ABSENCE')), ADD CONSTRAINT time_entries_source_check CHECK (source IN ('MANUAL','TIMER','IMPORT','MOBILE','API')), ADD CONSTRAINT time_entries_status_check CHECK (status IN ('DRAFT','SUBMITTED','APPROVED','LOCKED'))`);
  pgm.sql(`ALTER TABLE timesheets ADD CONSTRAINT timesheets_employee_fk FOREIGN KEY (tenant_id,employee_id) REFERENCES employees(tenant_id,id) ON DELETE RESTRICT, ADD CONSTRAINT timesheets_period_check CHECK (period_start <= period_end), ADD CONSTRAINT timesheets_status_check CHECK (status IN ('DRAFT','SUBMITTED','APPROVED','REJECTED','LOCKED'))`);
  pgm.createIndex('time_entries',['tenant_id','employee_id','work_date']); pgm.createIndex('time_entries',['tenant_id','work_date']); pgm.createIndex('time_entries',['tenant_id','status']); pgm.createIndex('timesheets',['tenant_id','employee_id','period_start','period_end'],{unique:true}); pgm.createIndex('timesheets',['tenant_id','status']);
  pgm.sql(`ALTER TABLE time_entries ENABLE ROW LEVEL SECURITY; ALTER TABLE time_entries FORCE ROW LEVEL SECURITY; CREATE POLICY tenant_all ON time_entries USING (tenant_id=public.tilivo_tenant_id()) WITH CHECK (tenant_id=public.tilivo_tenant_id()); ALTER TABLE timesheets ENABLE ROW LEVEL SECURITY; ALTER TABLE timesheets FORCE ROW LEVEL SECURITY; CREATE POLICY tenant_all ON timesheets USING (tenant_id=public.tilivo_tenant_id()) WITH CHECK (tenant_id=public.tilivo_tenant_id()); ALTER TABLE timesheet_approval_history ENABLE ROW LEVEL SECURITY; ALTER TABLE timesheet_approval_history FORCE ROW LEVEL SECURITY; CREATE POLICY tenant_all ON timesheet_approval_history USING (tenant_id=public.tilivo_tenant_id()) WITH CHECK (tenant_id=public.tilivo_tenant_id()); GRANT SELECT,INSERT,UPDATE,DELETE ON time_entries,timesheets,timesheet_approval_history TO tilivo_runtime`);
  pgm.sql(`INSERT INTO permissions (key,description) VALUES ('time.read','Read time tracking'),('time.create','Create time entries'),('time.update','Update time entries'),('time.submit','Submit timesheets'),('time.approve','Approve or reject timesheets'),('time.lock','Lock or reopen timesheets'),('time.manage_all','Manage all employee time') ON CONFLICT (key) DO NOTHING; INSERT INTO role_permissions(tenant_id,role_id,permission_id) SELECT r.tenant_id,r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.name IN ('Owner','Admin','Accountant') AND p.key LIKE 'time.%' ON CONFLICT (role_id,permission_id) DO NOTHING`);
};
exports.down = (pgm) => { pgm.dropTable('timesheet_approval_history'); pgm.dropTable('timesheets'); pgm.dropTable('time_entries'); pgm.sql(`DELETE FROM role_permissions rp USING permissions p WHERE rp.permission_id=p.id AND p.key LIKE 'time.%'; DELETE FROM permissions WHERE key LIKE 'time.%'`); };
