import type { Db } from '../db/pool';
import { AppError, ErrorCodes } from '../lib/errors';
import { isValidIban, normalizeIban } from '../lib/bankNormalization';
import { withTenantTransaction } from './tenantService';

export function normalizeFinnishPersonalId(value: string | null | undefined): string | null { const clean = String(value ?? '').trim().toUpperCase(); return clean || null; }
export function isValidFinnishPersonalId(value: string): boolean { const id = normalizeFinnishPersonalId(value) ?? ''; return /^(?:\d{6}[+\-A]\d{3}[0-9A-Y]|\d{6}[A-FY]\d{3}[0-9A-Y])$/.test(id); }
export function maskSensitive(value: string | null | undefined, visible = 4): string | null { if (!value) return null; return `${'•'.repeat(Math.max(0, value.length - visible))}${value.slice(-visible)}`; }
const date = (value: unknown) => value === undefined || value === null || value === '' ? null : String(value).slice(0, 10);

function validateEmployee(input: any, sensitive: boolean) {
  if (!String(input.first_name ?? '').trim() || !String(input.last_name ?? '').trim()) throw new AppError(ErrorCodes.invalidRequest, 'First and last name are required', 400);
  if (input.email && !/^\S+@\S+\.\S+$/.test(String(input.email))) throw new AppError(ErrorCodes.invalidRequest, 'Invalid email', 400);
  if (sensitive && input.personal_identity_code && !isValidFinnishPersonalId(String(input.personal_identity_code))) throw new AppError(ErrorCodes.invalidRequest, 'Invalid Finnish personal identity code', 400);
  if (sensitive && input.iban && !isValidIban(String(input.iban))) throw new AppError(ErrorCodes.invalidRequest, 'Invalid IBAN', 400);
  for (const key of ['withholding_percent', 'additional_percent']) if (input[key] !== undefined && input[key] !== null && (Number(input[key]) < 0 || Number(input[key]) > 100)) throw new AppError(ErrorCodes.invalidRequest, `${key} must be between 0 and 100`, 400);
}
export async function listEmployees(pool: Db, tenantId: string, filters: any = {}) { return withTenantTransaction(pool, tenantId, async (client) => { const values: any[] = [tenantId]; const where = ['e.tenant_id = $1']; if (filters.status) { values.push(String(filters.status).toUpperCase()); where.push(`e.status = $${values.length}`); } if (filters.search) { values.push(`%${filters.search}%`); where.push(`(e.first_name ILIKE $${values.length} OR e.last_name ILIKE $${values.length} OR e.employee_number ILIKE $${values.length} OR e.email ILIKE $${values.length})`); } const limit = Math.min(Math.max(Number(filters.limit ?? 50), 1), 200); const offset = Math.max(Number(filters.offset ?? 0), 0); const result = await client.query(`SELECT e.id,e.employee_number,e.first_name,e.last_name,e.preferred_name,e.email,e.phone,e.status,e.created_at,(SELECT job_title FROM employments em WHERE em.employee_id=e.id AND em.tenant_id=e.tenant_id AND em.active LIMIT 1) AS job_title,(SELECT employment_type FROM employments em WHERE em.employee_id=e.id AND em.tenant_id=e.tenant_id AND em.active LIMIT 1) AS employment_type,(SELECT start_date FROM employments em WHERE em.employee_id=e.id AND em.tenant_id=e.tenant_id AND em.active LIMIT 1) AS start_date FROM employees e WHERE ${where.join(' AND ')} ORDER BY e.last_name,e.first_name LIMIT $${values.length + 1} OFFSET $${values.length + 2}`, [...values, limit, offset]); const count = await client.query(`SELECT count(*)::int AS total FROM employees e WHERE ${where.join(' AND ')}`, values); return { employees: result.rows, total: count.rows[0]?.total ?? 0 }; }); }
export async function getEmployee(pool: Db, tenantId: string, id: string, sensitive: boolean) { return withTenantTransaction(pool, tenantId, async (client) => { const e = await client.query('SELECT * FROM employees WHERE id=$1 AND tenant_id=$2', [id, tenantId]); if (!e.rows[0]) throw new AppError(ErrorCodes.invalidRequest, 'Employee not found', 404); const em = await client.query('SELECT * FROM employments WHERE employee_id=$1 AND tenant_id=$2 ORDER BY start_date DESC', [id, tenantId]); return { ...e.rows[0], ...(sensitive ? {} : { personal_identity_code: maskSensitive(e.rows[0].personal_identity_code, 2), iban: maskSensitive(e.rows[0].iban, 4), tax_card_type: undefined, withholding_percent: undefined, additional_percent: undefined, income_limit: undefined, pension_policy_reference: undefined }), employments: em.rows }; }); }
export async function createEmployee(pool: Db, tenantId: string, input: any) { return withTenantTransaction(pool, tenantId, async (client) => { validateEmployee(input, true); const number = input.employee_number ? String(input.employee_number).trim() : String((await client.query("SELECT COALESCE(max(NULLIF(employee_number,'')::int),0)+1 AS next FROM employees WHERE tenant_id=$1 AND employee_number ~ '^[0-9]+$'", [tenantId])).rows[0].next).padStart(4, '0'); const result = await client.query(`INSERT INTO employees (tenant_id,employee_number,first_name,last_name,preferred_name,personal_identity_code,date_of_birth,nationality,email,phone,address_line1,address_line2,postal_code,city,country,language,iban,bic,account_holder_name,tax_card_type,withholding_percent,additional_percent,income_limit,tax_valid_from,tax_valid_to,tax_source_reference,pension_insurance_type,pension_provider,pension_policy_reference,accident_insurance_ready,unemployment_insurance_applicable,home_municipality,default_travel_origin,company_car_ready,mileage_eligible,per_diem_eligible,emergency_contact_name,emergency_contact_relationship,emergency_contact_phone,internal_notes) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27,$28,$29,$30,$31,$32,$33,$34,$35,$36,$37,$38,$39,$40) RETURNING *`, [tenantId,number,input.first_name.trim(),input.last_name.trim(),input.preferred_name ?? null,normalizeFinnishPersonalId(input.personal_identity_code),date(input.date_of_birth),input.nationality ?? null,input.email ?? null,input.phone ?? null,input.address_line1 ?? null,input.address_line2 ?? null,input.postal_code ?? null,input.city ?? null,input.country ?? 'FI',input.language ?? 'FI',input.iban ? normalizeIban(input.iban) : null,input.bic ?? null,input.account_holder_name ?? null,input.tax_card_type ?? null,input.withholding_percent ?? null,input.additional_percent ?? null,input.income_limit ?? null,date(input.tax_valid_from),date(input.tax_valid_to),input.tax_source_reference ?? null,input.pension_insurance_type ?? null,input.pension_provider ?? null,input.pension_policy_reference ?? null,Boolean(input.accident_insurance_ready),input.unemployment_insurance_applicable ?? null,input.home_municipality ?? null,input.default_travel_origin ?? null,Boolean(input.company_car_ready),Boolean(input.mileage_eligible),Boolean(input.per_diem_eligible),input.emergency_contact_name ?? null,input.emergency_contact_relationship ?? null,input.emergency_contact_phone ?? null,input.internal_notes ?? null]); return result.rows[0]; }); }
export async function updateEmployee(pool: Db, tenantId: string, id: string, input: any, sensitive: boolean) { return withTenantTransaction(pool, tenantId, async (client) => { validateEmployee({ ...input, first_name: input.first_name ?? 'ok', last_name: input.last_name ?? 'ok' }, sensitive); const fields: Record<string, string> = { status:'status', first_name:'first_name',last_name:'last_name',preferred_name:'preferred_name',date_of_birth:'date_of_birth',nationality:'nationality',email:'email',phone:'phone',address_line1:'address_line1',address_line2:'address_line2',postal_code:'postal_code',city:'city',country:'country',language:'language',emergency_contact_name:'emergency_contact_name',emergency_contact_relationship:'emergency_contact_relationship',emergency_contact_phone:'emergency_contact_phone',internal_notes:'internal_notes',home_municipality:'home_municipality',default_travel_origin:'default_travel_origin',company_car_ready:'company_car_ready',mileage_eligible:'mileage_eligible',per_diem_eligible:'per_diem_eligible' }; if (sensitive) Object.assign(fields,{personal_identity_code:'personal_identity_code',iban:'iban',bic:'bic',account_holder_name:'account_holder_name',tax_card_type:'tax_card_type',withholding_percent:'withholding_percent',additional_percent:'additional_percent',income_limit:'income_limit',tax_valid_from:'tax_valid_from',tax_valid_to:'tax_valid_to',tax_source_reference:'tax_source_reference',pension_insurance_type:'pension_insurance_type',pension_provider:'pension_provider',pension_policy_reference:'pension_policy_reference',accident_insurance_ready:'accident_insurance_ready',unemployment_insurance_applicable:'unemployment_insurance_applicable'}); const sets: string[] = []; const values: any[] = [id, tenantId]; for (const [key, column] of Object.entries(fields)) { if (input[key] === undefined) continue; values.push(['date_of_birth','tax_valid_from','tax_valid_to'].includes(key) ? date(input[key]) : key === 'personal_identity_code' ? normalizeFinnishPersonalId(input[key]) : key === 'iban' ? normalizeIban(input[key]) : input[key]); sets.push(`${column}=$${values.length}`); } if (!sets.length) throw new AppError(ErrorCodes.invalidRequest, 'Nothing to update', 400); sets.push('updated_at=now()'); const r = await client.query(`UPDATE employees SET ${sets.join(',')} WHERE id=$1 AND tenant_id=$2 RETURNING *`, values); if (!r.rows[0]) throw new AppError(ErrorCodes.invalidRequest, 'Employee not found', 404); return r.rows[0]; }); }
export async function createEmployment(pool: Db, tenantId: string, employeeId: string, input: any) { return withTenantTransaction(pool, tenantId, async (client) => { if (!input.job_title || !input.start_date) throw new AppError(ErrorCodes.invalidRequest, 'Job title and start date are required', 400); await client.query('UPDATE employments SET active=false,updated_at=now() WHERE employee_id=$1 AND tenant_id=$2 AND active', [employeeId, tenantId]); const r = await client.query(`INSERT INTO employments (tenant_id,employee_id,employment_type,contract_type,start_date,end_date,job_title,department,cost_center,project_code,work_location,weekly_hours,daily_hours,working_days_per_week,work_schedule_type,pay_type,monthly_salary,hourly_rate,daily_rate,currency,collective_agreement,active) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,true) RETURNING *`, [tenantId,employeeId,input.employment_type??'PERMANENT',input.contract_type??'FULL_TIME',date(input.start_date),date(input.end_date),input.job_title,input.department??null,input.cost_center??null,input.project_code??null,input.work_location??null,input.weekly_hours??null,input.daily_hours??null,input.working_days_per_week??null,input.work_schedule_type??null,input.pay_type??'MONTHLY',input.monthly_salary??null,input.hourly_rate??null,input.daily_rate??null,input.currency??'EUR',input.collective_agreement??null]); return r.rows[0]; }); }
