import { normalizeSalesLanguage, type SalesLanguage } from './salesMath';

export type InvoicePdfKind = 'INVOICE' | 'CREDIT_NOTE' | 'ADVANCE_INVOICE' | 'REMINDER';

export interface PdfLabelSet {
  invoice: string;
  creditNote: string;
  advanceInvoice: string;
  reminder: string;
  invoiceNumber: string;
  date: string;
  invoiceDate: string;
  dueDate: string;
  customer: string;
  seller: string;
  billTo: string;
  description: string;
  quantity: string;
  unit: string;
  unitPrice: string;
  discount: string;
  net: string;
  vat: string;
  vatTotal: string;
  total: string;
  paymentTerms: string;
  reference: string;
  iban: string;
  bic: string;
  accountHolder: string;
  amountDue: string;
  amountPaid: string;
  openBalance: string;
  advanceApplied: string;
  creditApplied: string;
  taxNotes: string;
  taxSummary: string;
  currency: string;
  businessId: string;
  vatId: string;
  issuedBy: string;
  reminderFee: string;
  lateInterest: string;
  interestDays: string;
  originalInvoice: string;
  originalDueDate: string;
  reminderDate: string;
  message: string;
  paymentReference: string;
  thankYou: string;
  footer: string;
}

export const PDF_LABELS: Record<'fi' | 'en' | 'et', PdfLabelSet> = {
  fi: {
    invoice: 'Lasku',
    creditNote: 'Hyvityslasku',
    advanceInvoice: 'Ennakkolasku',
    reminder: 'Maksumuistutus',
    invoiceNumber: 'Laskun numero',
    date: 'Päiväys',
    invoiceDate: 'Laskun päiväys',
    dueDate: 'Eräpäivä',
    customer: 'Asiakas',
    seller: 'Myyjä',
    billTo: 'Maksaja',
    description: 'Kuvaus',
    quantity: 'Määrä',
    unit: 'Yksikkö',
    unitPrice: 'Yksikköhinta',
    discount: 'Alennus',
    net: 'Netto',
    vat: 'ALV',
    vatTotal: 'ALV yhteensä',
    total: 'Yhteensä',
    paymentTerms: 'Maksuehto',
    reference: 'Viitenumero',
    iban: 'IBAN',
    bic: 'BIC',
    accountHolder: 'Tilin haltija',
    amountDue: 'Maksettava yhteensä',
    amountPaid: 'Maksettu',
    openBalance: 'Avoin saldo',
    advanceApplied: 'Ennakot',
    creditApplied: 'Hyvitykset',
    taxNotes: 'Verotiedot',
    taxSummary: 'Veroyhteenveto',
    currency: 'Valuutta',
    businessId: 'Y-tunnus',
    vatId: 'ALV-tunnus',
    issuedBy: 'Tilivo',
    reminderFee: 'Muistutusmaksu',
    lateInterest: 'Viivästyskorko',
    interestDays: 'Viivästyspäivät',
    originalInvoice: 'Alkuperäinen lasku',
    originalDueDate: 'Alkuperäinen eräpäivä',
    reminderDate: 'Muistutuksen päiväys',
    message: 'Viesti',
    paymentReference: 'Maksuviite',
    thankYou: 'Kiitos asiakkuudestanne.',
    footer: 'Asiakirjan on tuottanut Tilivo.',
  },
  en: {
    invoice: 'Invoice',
    creditNote: 'Credit note',
    advanceInvoice: 'Advance invoice',
    reminder: 'Reminder',
    invoiceNumber: 'Invoice number',
    date: 'Date',
    invoiceDate: 'Invoice date',
    dueDate: 'Due date',
    customer: 'Customer',
    seller: 'Seller',
    billTo: 'Bill to',
    description: 'Description',
    quantity: 'Quantity',
    unit: 'Unit',
    unitPrice: 'Unit price',
    discount: 'Discount',
    net: 'Net',
    vat: 'VAT',
    vatTotal: 'VAT total',
    total: 'Total',
    paymentTerms: 'Payment terms',
    reference: 'Reference',
    iban: 'IBAN',
    bic: 'BIC',
    accountHolder: 'Account holder',
    amountDue: 'Amount due',
    amountPaid: 'Amount paid',
    openBalance: 'Open balance',
    advanceApplied: 'Advance applied',
    creditApplied: 'Credit applied',
    taxNotes: 'Tax notes',
    taxSummary: 'Tax summary',
    currency: 'Currency',
    businessId: 'Business ID',
    vatId: 'VAT ID',
    issuedBy: 'Tilivo',
    reminderFee: 'Reminder fee',
    lateInterest: 'Late interest',
    interestDays: 'Interest days',
    originalInvoice: 'Original invoice',
    originalDueDate: 'Original due date',
    reminderDate: 'Reminder date',
    message: 'Message',
    paymentReference: 'Payment reference',
    thankYou: 'Thank you for your business.',
    footer: 'Document generated by Tilivo.',
  },
  et: {
    invoice: 'Arve',
    creditNote: 'Kreeditarve',
    advanceInvoice: 'Ettemaksuarve',
    reminder: 'Makse meeldetuletus',
    invoiceNumber: 'Arve number',
    date: 'Kuupäev',
    invoiceDate: 'Arve kuupäev',
    dueDate: 'Maksetähtaeg',
    customer: 'Klient',
    seller: 'Müüja',
    billTo: 'Maksja',
    description: 'Kirjeldus',
    quantity: 'Kogus',
    unit: 'Ühik',
    unitPrice: 'Ühiku hind',
    discount: 'Allahindlus',
    net: 'Neto',
    vat: 'KM',
    vatTotal: 'KM kokku',
    total: 'Kokku',
    paymentTerms: 'Maksetingimused',
    reference: 'Viitenumber',
    iban: 'IBAN',
    bic: 'BIC',
    accountHolder: 'Konto omanik',
    amountDue: 'Tasumisele kuuluv summa',
    amountPaid: 'Makstud',
    openBalance: 'Avatud saldo',
    advanceApplied: 'Ettemaks',
    creditApplied: 'Kreedit',
    taxNotes: 'Käibemaksu märkused',
    taxSummary: 'KM kokkuvõte',
    currency: 'Valuuta',
    businessId: 'Registrikood',
    vatId: 'KM-kohustuslase number',
    issuedBy: 'Tilivo',
    reminderFee: 'Meeldetuletuse tasu',
    lateInterest: 'Viivis',
    interestDays: 'Viivise päevad',
    originalInvoice: 'Algne arve',
    originalDueDate: 'Algne maksetähtaeg',
    reminderDate: 'Meeldetuletuse kuupäev',
    message: 'Sõnum',
    paymentReference: 'Viitenumber',
    thankYou: 'Täname koostöö eest.',
    footer: 'Dokumendi koostas Tilivo.',
  },
};

export type PdfLabelKey = keyof PdfLabelSet;

export function pdfLabelsFor(value: unknown): PdfLabelSet {
  const language: SalesLanguage = normalizeSalesLanguage(value);
  return PDF_LABELS[language];
}

export function pdfLabel(key: PdfLabelKey, language: unknown): string {
  return pdfLabelsFor(language)[key];
}

export function pdfTitle(kind: InvoicePdfKind, language: unknown): string {
  const labels = pdfLabelsFor(language);
  switch (kind) {
    case 'CREDIT_NOTE': return labels.creditNote.toUpperCase();
    case 'ADVANCE_INVOICE': return labels.advanceInvoice.toUpperCase();
    case 'REMINDER': return labels.reminder.toUpperCase();
    default: return labels.invoice.toUpperCase();
  }
}
