import type { Db } from '../db/pool';
import { AppError, ErrorCodes } from '../lib/errors';
import { withTenantTransaction } from './tenantService';
const dateRe=/^\d{4}-\d{2}-\d{2}$/;const types=['REGULAR','OVERTIME','EVENING','NIGHT','SUNDAY','HOLIDAY_WORK','OTHER_WORK','SICK_LEAVE','ANNUAL_LEAVE','UNPAID_LEAVE','FAMILY_LEAVE','TRAINING','OTHER_ABSENCE'];
function mins(x:any){if(x.duration_minutes!==undefined)return Number(x.duration_minutes);if(!x.start_time||!x.end_time)return NaN;let n=Math.round((new Date(x.end_time).getTime()-new Date(x.start_time).getTime())/60000);if(n<0)n+=1440;return n;}
function valid(x:any){const n=mins(x),b=Number(x.break_minutes??0);if(!dateRe.test(String(x.work_date??''))||!Number.isInteger(n)||n<0||!Number.isInteger(b)||b<0||b>n)throw new AppError(ErrorCodes.invalidRequest,'Invalid work date, duration or break',400);if(!['WORK','ABSENCE'].includes(x.entry_kind??'WORK')||!types.includes(x.work_type??'REGULAR'))throw new AppError(ErrorCodes.invalidRequest,'Invalid time entry type',400);return n;}
export async function listEntries(pool:Db,tenantId:string,f:any={}){return withTenantTransaction(pool,tenantId,async c=>{const v:any[]=[tenantId];const w:string[]=['t.tenant_id=$1'];for(const k of ['employee_id','status','work_type'])if(f[k]){v.push(f[k]);w.push(`t.${k} = $${v.length}`)}if(f.from){v.push(f.from);w.push(`t.work_date >= $${v.length}`)}if(f.to){v.push(f.to);w.push(`t.work_date <= $${v.length}`)}const r=await c.query(`SELECT t.*,e.first_name,e.last_name,e.employee_number FROM time_entries t JOIN employees e ON e.id=t.employee_id AND e.tenant_id=t.tenant_id WHERE ${w.join(' AND ')} ORDER BY t.work_date DESC,t.start_time DESC LIMIT 200`,v);return {entries:r.rows};});}
export async function createEntry(pool:Db,tenantId:string,userId:string,x:any){return withTenantTransaction(pool,tenantId,async c=>{const n=valid(x);const e=await c.query('SELECT id,status FROM employees WHERE id=$1 AND tenant_id=$2',[x.employee_id,tenantId]);if(!e.rows[0])throw new AppError(ErrorCodes.invalidRequest,'Employee not found',404);if(e.rows[0].status==='TERMINATED')throw new AppError(ErrorCodes.invalidRequest,'Employee is terminated',400);const r=await c.query(`INSERT INTO time_entries(tenant_id,employee_id,employment_id,work_date,start_time,end_time,duration_minutes,break_minutes,entry_kind,work_type,project_code,project_name,cost_center,work_location,description,source,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17) RETURNING *`,[tenantId,x.employee_id,x.employment_id??null,x.work_date,x.start_time??null,x.end_time??null,n,x.break_minutes??0,x.entry_kind??'WORK',x.work_type??'REGULAR',x.project_code??null,x.project_name??null,x.cost_center??null,x.work_location??null,x.description??null,x.source??'MANUAL',userId]);return r.rows[0];});}
export async function summary(pool:Db,tenantId:string,f:any){return withTenantTransaction(pool,tenantId,async c=>{const r=await c.query(`SELECT work_date,sum(CASE WHEN entry_kind='WORK' THEN duration_minutes-break_minutes ELSE 0 END)::int total_work,sum(CASE WHEN work_type='REGULAR' THEN duration_minutes-break_minutes ELSE 0 END)::int regular,sum(CASE WHEN work_type='OVERTIME' THEN duration_minutes-break_minutes ELSE 0 END)::int overtime,sum(CASE WHEN work_type='EVENING' THEN duration_minutes-break_minutes ELSE 0 END)::int evening,sum(CASE WHEN work_type='NIGHT' THEN duration_minutes-break_minutes ELSE 0 END)::int night,sum(CASE WHEN work_type='SUNDAY' THEN duration_minutes-break_minutes ELSE 0 END)::int sunday,sum(CASE WHEN entry_kind='ABSENCE' THEN duration_minutes ELSE 0 END)::int absence,sum(break_minutes)::int breaks FROM time_entries WHERE tenant_id=$1 AND work_date BETWEEN $2 AND $3 GROUP BY work_date ORDER BY work_date`,[tenantId,f.from,f.to]);return {daily:r.rows};});}
export async function timesheets(pool:Db,tenantId:string){return withTenantTransaction(pool,tenantId,async c=>({timesheets:(await c.query(`SELECT s.*,e.first_name,e.last_name,coalesce(sum(CASE WHEN t.entry_kind='WORK' THEN t.duration_minutes-t.break_minutes ELSE 0 END),0)::int total_work FROM timesheets s JOIN employees e ON e.id=s.employee_id AND e.tenant_id=s.tenant_id LEFT JOIN time_entries t ON t.tenant_id=s.tenant_id AND t.employee_id=s.employee_id AND t.work_date BETWEEN s.period_start AND s.period_end WHERE s.tenant_id=$1 GROUP BY s.id,e.first_name,e.last_name ORDER BY s.period_start DESC`,[tenantId])).rows}));}
export async function createTimesheet(pool:Db,tenantId:string,b:any){return withTenantTransaction(pool,tenantId,async c=>{if(!dateRe.test(String(b.period_start))||!dateRe.test(String(b.period_end)))throw new AppError(ErrorCodes.invalidRequest,'Invalid period',400);return (await c.query('INSERT INTO timesheets(tenant_id,employee_id,period_start,period_end) VALUES($1,$2,$3,$4) RETURNING *',[tenantId,b.employee_id,b.period_start,b.period_end])).rows[0];});}
export async function timesheetAction(pool:Db,tenantId:string,userId:string,id:string,action:string,reason?:string){return withTenantTransaction(pool,tenantId,async c=>{const next:any={submit:'SUBMITTED',approve:'APPROVED',reject:'REJECTED',lock:'LOCKED',reopen:'REJECTED'};if(!next[action])throw new AppError(ErrorCodes.invalidRequest,'Invalid timesheet action',400);const r=await c.query(`UPDATE timesheets SET status=$1,submitted_at=CASE WHEN $1='SUBMITTED' THEN now() ELSE submitted_at END,submitted_by=CASE WHEN $1='SUBMITTED' THEN $2 ELSE submitted_by END,approved_at=CASE WHEN $1='APPROVED' THEN now() ELSE approved_at END,approved_by=CASE WHEN $1='APPROVED' THEN $2 ELSE approved_by END,rejected_at=CASE WHEN $1='REJECTED' THEN now() ELSE rejected_at END,rejection_reason=CASE WHEN $1='REJECTED' THEN $3 ELSE rejection_reason END,locked_at=CASE WHEN $1='LOCKED' THEN now() ELSE locked_at END,updated_at=now() WHERE id=$4 AND tenant_id=$5 RETURNING *`,[next[action],userId,reason??null,id,tenantId]);if(!r.rows[0])throw new AppError(ErrorCodes.invalidRequest,'Timesheet not found',404);await c.query('INSERT INTO timesheet_approval_history(tenant_id,timesheet_id,actor_id,action,reason) VALUES($1,$2,$3,$4,$5)',[tenantId,id,userId,action,reason??null]);return r.rows[0];});}
