import type { FastifyInstance, FastifyRequest } from 'fastify';
import type { AppConfig } from '../config/env';
import type { Db } from '../db/pool';
import { AppError, ErrorCodes } from '../lib/errors';
import { hasPermission, requirePermission, resolveTenantAccess } from '../services/tenantService';
import { resolveSessionUser } from '../services/sessionContext';
import { writeAuditEvent } from '../services/audit';
import { createEmployee, createEmployment, getEmployee, listEmployees, updateEmployee } from '../services/employeeService';

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
async function context(request: FastifyRequest, db: Db, config: AppConfig) { const { user } = await resolveSessionUser(db, request, config); const tenantId = String(request.headers['x-tilivo-tenant-id'] ?? '').toLowerCase(); if (!UUID.test(tenantId)) throw new AppError(ErrorCodes.tenantInvalid, 'Valid tenant id required', 400); await resolveTenantAccess(db,user.id,tenantId); return { userId:user.id,tenantId }; }
export async function employeeRoutes(app: FastifyInstance, options: { db: Db; config: AppConfig }) { const {db,config}=options;
  app.get('/api/v1/employees', async (request)=>{ const {userId,tenantId}=await context(request,db,config); await requirePermission(db,userId,tenantId,'employees.read'); const q=request.query as Record<string,unknown>; return listEmployees(db,tenantId,{search:typeof q.search==='string'?q.search:undefined,status:typeof q.status==='string'?q.status:undefined,limit:q.limit,offset:q.offset}); });
  app.post<{Body:Record<string,unknown>}>('/api/v1/employees',async(request,reply)=>{const {userId,tenantId}=await context(request,db,config); await requirePermission(db,userId,tenantId,'employees.create'); const employee=await createEmployee(db,tenantId,request.body??{}); await writeAuditEvent(db,'EMPLOYEE.CREATED',request,{userId,tenantId,objectType:'employee',objectId:String(employee.id),metadata:{employee_number:employee.employee_number}}); return reply.code(201).send({employee});});
  app.get<{Params:{id:string}}>('/api/v1/employees/:id',async(request)=>{const {userId,tenantId}=await context(request,db,config); await requirePermission(db,userId,tenantId,'employees.read'); const id=String(request.params.id).toLowerCase(); if(!UUID.test(id)) throw new AppError(ErrorCodes.invalidRequest,'Invalid employee id',400); const sensitive=await hasPermission(db,userId,tenantId,'employees.manage_sensitive'); return {employee:await getEmployee(db,tenantId,id,sensitive)};});
  app.patch<{Params:{id:string};Body:Record<string,unknown>}>('/api/v1/employees/:id',async(request)=>{const {userId,tenantId}=await context(request,db,config); await requirePermission(db,userId,tenantId,'employees.update'); const sensitive=await hasPermission(db,userId,tenantId,'employees.manage_sensitive'); const employee=await updateEmployee(db,tenantId,String(request.params.id).toLowerCase(),request.body??{},sensitive); await writeAuditEvent(db,sensitive?'EMPLOYEE.SENSITIVE_UPDATED':'EMPLOYEE.UPDATED',request,{userId,tenantId,objectType:'employee',objectId:String(employee.id),metadata:{fields:Object.keys(request.body??{}).filter((x)=>!['personal_identity_code','iban'].includes(x))}}); return {employee};});
  app.post<{Params:{id:string};Body:Record<string,unknown>}>('/api/v1/employees/:id/employments',async(request,reply)=>{const {userId,tenantId}=await context(request,db,config); await requirePermission(db,userId,tenantId,'employees.update'); const employment=await createEmployment(db,tenantId,String(request.params.id).toLowerCase(),request.body??{}); await writeAuditEvent(db,'EMPLOYMENT.CREATED',request,{userId,tenantId,objectType:'employment',objectId:String(employment.id),metadata:{employee_id:String(request.params.id)}}); return reply.code(201).send({employment});});
  app.get<{Params:{id:string}}>('/api/v1/employees/:id/employments',async(request)=>{const {userId,tenantId}=await context(request,db,config); await requirePermission(db,userId,tenantId,'employees.read'); const detail=await getEmployee(db,tenantId,String(request.params.id).toLowerCase(),false); return {employments:detail.employments};});
  app.post<{Params:{id:string};Body:Record<string,unknown>}>('/api/v1/employees/:id/terminate',async(request)=>{const {userId,tenantId}=await context(request,db,config); await requirePermission(db,userId,tenantId,'employees.terminate'); const employeeId=String(request.params.id).toLowerCase(); const result=await updateEmployee(db,tenantId,employeeId,{status:'TERMINATED'},false); await writeAuditEvent(db,'EMPLOYEE.TERMINATED',request,{userId,tenantId,objectType:'employee',objectId:employeeId,metadata:{end_date:request.body?.end_date??null,reason:request.body?.reason??null}}); return {employee:result};});
  app.post<{Params:{id:string}}>('/api/v1/employees/:id/reactivate',async(request)=>{const {userId,tenantId}=await context(request,db,config); await requirePermission(db,userId,tenantId,'employees.terminate'); const employeeId=String(request.params.id).toLowerCase(); const result=await updateEmployee(db,tenantId,employeeId,{status:'ACTIVE'},false); await writeAuditEvent(db,'EMPLOYEE.REACTIVATED',request,{userId,tenantId,objectType:'employee',objectId:employeeId}); return {employee:result};});
}
