import type { FastifyInstance, FastifyRequest } from 'fastify';
import type { AppConfig } from '../config/env';
import type { Db } from '../db/pool';
import { AppError, ErrorCodes } from '../lib/errors';
import { hasPermission, requirePermission, resolveTenantAccess } from '../services/tenantService';
import { resolveSessionUser } from '../services/sessionContext';
import { writeAuditEvent } from '../services/audit';
import { createEntry, createTimesheet, deleteEntry, employeeIdForUser, getEntry, getTimesheet, listEntries, summary, timesheetAction, timesheets, updateEntry } from '../services/timeTrackingService';
const UUID = /^[0-9a-f-]{36}$/i;
async function ctx(r: FastifyRequest, db: Db, config: AppConfig) { const { user } = await resolveSessionUser(db, r, config); const tenantId = String(r.headers['x-tilivo-tenant-id'] ?? '').toLowerCase(); if (!UUID.test(tenantId)) throw new AppError(ErrorCodes.tenantInvalid, 'Valid tenant id required', 400); await resolveTenantAccess(db, user.id, tenantId); return { userId: user.id, tenantId }; }
async function ownOrManage(db: Db, userId: string, tenantId: string, employeeId: string) { if (await hasPermission(db, userId, tenantId, 'time.manage_all')) return; const own = await employeeIdForUser(db, tenantId, userId); if (own !== employeeId) throw new AppError(ErrorCodes.tenantAccessDenied, 'Employee time access denied', 403); }
export async function timeTrackingRoutes(app: FastifyInstance, o: { db: Db; config: AppConfig }) { const { db, config } = o;
  app.get('/api/v1/time-tracking/entries', async r => { const x = await ctx(r, db, config); await requirePermission(db, x.userId, x.tenantId, 'time.read'); const manage = await hasPermission(db, x.userId, x.tenantId, 'time.manage_all'); const q: any = r.query; if (!manage) q.employee_id = await employeeIdForUser(db, x.tenantId, x.userId) ?? '__none__'; return listEntries(db, x.tenantId, q); });
  app.get<{ Params: { id: string } }>('/api/v1/time-tracking/entries/:id', async r => { const x = await ctx(r, db, config); await requirePermission(db, x.userId, x.tenantId, 'time.read'); const e = await getEntry(db, x.tenantId, r.params.id); await ownOrManage(db, x.userId, x.tenantId, e.employee_id); return { entry: e }; });
  app.post<{ Body: Record<string, unknown> }>('/api/v1/time-tracking/entries', async (r, reply) => { const x = await ctx(r, db, config); await requirePermission(db, x.userId, x.tenantId, 'time.create'); await ownOrManage(db, x.userId, x.tenantId, String(r.body?.employee_id)); const entry = await createEntry(db, x.tenantId, x.userId, r.body ?? {}); await writeAuditEvent(db, 'TIME_ENTRY.CREATED', r, { userId: x.userId, tenantId: x.tenantId, objectType: 'time_entry', objectId: String(entry.id) }); return reply.code(201).send({ entry }); });
  app.patch<{ Params: { id: string }; Body: Record<string, unknown> }>('/api/v1/time-tracking/entries/:id', async r => { const x = await ctx(r, db, config); await requirePermission(db, x.userId, x.tenantId, 'time.update'); const old = await getEntry(db, x.tenantId, r.params.id); await ownOrManage(db, x.userId, x.tenantId, old.employee_id); const entry = await updateEntry(db, x.tenantId, r.params.id, r.body ?? {}); await writeAuditEvent(db, 'TIME_ENTRY.UPDATED', r, { userId: x.userId, tenantId: x.tenantId, objectType: 'time_entry', objectId: r.params.id }); return { entry }; });
  app.delete<{ Params: { id: string } }>('/api/v1/time-tracking/entries/:id', async r => { const x = await ctx(r, db, config); await requirePermission(db, x.userId, x.tenantId, 'time.update'); const old = await getEntry(db, x.tenantId, r.params.id); await ownOrManage(db, x.userId, x.tenantId, old.employee_id); const result = await deleteEntry(db, x.tenantId, r.params.id); await writeAuditEvent(db, 'TIME_ENTRY.DELETED', r, { userId: x.userId, tenantId: x.tenantId, objectType: 'time_entry', objectId: r.params.id }); return result; });
  app.get('/api/v1/time-tracking/summary', async r => { const x = await ctx(r, db, config); await requirePermission(db, x.userId, x.tenantId, 'time.read'); const q: any = r.query; if (!(await hasPermission(db, x.userId, x.tenantId, 'time.manage_all'))) q.employee_id = await employeeIdForUser(db, x.tenantId, x.userId) ?? '__none__'; return summary(db, x.tenantId, q); });
  app.get('/api/v1/time-tracking/timesheets', async r => { const x = await ctx(r, db, config); await requirePermission(db, x.userId, x.tenantId, 'time.read'); return timesheets(db, x.tenantId); });
  app.get<{ Params: { id: string } }>('/api/v1/time-tracking/timesheets/:id', async r => { const x = await ctx(r, db, config); await requirePermission(db, x.userId, x.tenantId, 'time.read'); return { timesheet: await getTimesheet(db, x.tenantId, r.params.id) }; });
  app.post<{ Body: Record<string, unknown> }>('/api/v1/time-tracking/timesheets', async (r, reply) => { const x = await ctx(r, db, config); await requirePermission(db, x.userId, x.tenantId, 'time.create'); await ownOrManage(db, x.userId, x.tenantId, String(r.body?.employee_id)); return reply.code(201).send({ timesheet: await createTimesheet(db, x.tenantId, r.body ?? {}) }); });
  for (const action of ['submit', 'approve', 'reject', 'lock', 'reopen']) app.post<{ Params: { id: string }; Body: Record<string, unknown> }>(`/api/v1/time-tracking/timesheets/:id/${action}`, async r => { const x = await ctx(r, db, config); const p = ['approve', 'reject'].includes(action) ? 'time.approve' : ['lock', 'reopen'].includes(action) ? 'time.lock' : 'time.submit'; await requirePermission(db, x.userId, x.tenantId, p); const sheet = await timesheetAction(db, x.tenantId, x.userId, r.params.id, action, String(r.body?.reason ?? '')); await writeAuditEvent(db, `TIMESHEET.${action.toUpperCase()}` as any, r, { userId: x.userId, tenantId: x.tenantId, objectType: 'timesheet', objectId: r.params.id }); return { timesheet: sheet }; });
}
