export const ErrorCodes = {
  internal: 'SYS-001',
  databaseUnreachable: 'DB-001',
  notFound: 'API-001',
  invalidRequest: 'API-002',
  config: 'CFG-001',
  authInvalidRequest: 'AUTH-001',
  authInvalidCredentials: 'AUTH-002',
  authEmailNotVerified: 'AUTH-003',
  authRateLimited: 'AUTH-004',
  authSessionInvalid: 'AUTH-005',
  authSessionExpired: 'AUTH-006',
  authVerificationTokenInvalid: 'AUTH-007',
  authResetTokenInvalid: 'AUTH-008',
  authTwoFactorRequired: 'AUTH-009',
  authTwoFactorInvalid: 'AUTH-010',
  authRecoveryCodeInvalid: 'AUTH-011',
  authCsrfInvalid: 'AUTH-012',
  authAccountDisabled: 'AUTH-013',
  authPasswordPolicy: 'AUTH-014',
  tenantInvalid: 'TENANT-001',
  tenantAccessDenied: 'TENANT-002',
  tenantSuspended: 'TENANT-003',
  tenantMembershipInactive: 'TENANT-004',
  memberNotFound: 'MEMBER-001',
  memberLastOwner: 'MEMBER-002',
  memberPermissionDenied: 'MEMBER-003',
  roleInvalid: 'ROLE-001',
  rolePermissionDenied: 'ROLE-002',
  documentInvalid: 'DOC-001',
  documentTooLarge: 'DOC-002',
  documentNotFound: 'DOC-003',
  auditNotFound: 'AUDIT-001',
  inboxDuplicate: 'INBOX-001',
  outboxClaim: 'OUTBOX-001',
  accountNotFound: 'ACC-001',
  accountInactive: 'ACC-002',
  duplicateAccountCode: 'ACC-003',
  periodNotFound: 'PERIOD-001',
  periodClosed: 'PERIOD-002',
  periodSoftClosed: 'PERIOD-003',
  invalidPeriodRange: 'PERIOD-004',
  journalNotFound: 'JRN-001',
  journalNotDraft: 'JRN-002',
  journalNotBalanced: 'JRN-003',
  journalLineInvalid: 'JRN-004',
  journalImmutable: 'JRN-005',
  journalAlreadyReversed: 'JRN-006',
  taxCodeNotFound: 'TAX-001',
  taxCodeInvalid: 'TAX-002',
  taxCodeDuplicate: 'TAX-003',
  fxRateNotFound: 'FX-001',
  fxRateDuplicate: 'FX-002',
  fxRateInvalid: 'FX-003',
  currencyNotFound: 'CUR-001',
  customerNotFound: 'CUST-001',
  customerInactive: 'CUST-002',
  invalidCustomer: 'CUST-003',
  invoiceNotFound: 'INV-001',
  invoiceNotDraft: 'INV-002',
  invoiceHasNoLines: 'INV-003',
  invalidInvoiceLine: 'INV-004',
  invalidDueDate: 'INV-005',
  numberSeriesNotFound: 'INV-006',
  accountMappingMissing: 'INV-007',
  invoiceTaxCodeInvalid: 'INV-008',
  invoiceImmutable: 'INV-009',
  alreadyCredited: 'INV-010',
  pdfNotReady: 'INV-011',
  referenceInvalid: 'INV-012',
  currencyInvalid: 'INV-013',
  supplierNotFound: 'SUP-001',
  supplierInactive: 'SUP-002',
  supplierMatchAmbiguous: 'SUP-003',
  purchaseNotFound: 'PUR-001',
  purchaseNotEditable: 'PUR-002',
  purchaseHasNoLines: 'PUR-003',
  invalidPurchaseLine: 'PUR-004',
  duplicatePurchase: 'PUR-005',
  approvalRequired: 'PUR-006',
  approverNotAllowed: 'PUR-007',
  purchaseAccountMappingMissing: 'PUR-008',
  taxMappingMissing: 'PUR-009',
  purchaseImmutable: 'PUR-010',
  invalidSourceDocument: 'PUR-011',
  ingestionFailed: 'PUR-012',
  unsupportedFormat: 'EINV-001',
  invalidXml: 'EINV-002',
  duplicateExternalEvent: 'EINV-003',
  missingRequiredField: 'EINV-004',
  extractionUnavailable: 'OCR-001',
  extractionFailed: 'OCR-002',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

export class AppError extends Error {
  constructor(
    readonly code: ErrorCode,
    message: string,
    readonly statusCode: number,
    readonly details?: unknown,
  ) {
    super(message);
    this.name = 'AppError';
  }
}

export function toErrorBody(code: string, message: string, traceId: string) {
  return {
    error: {
      code,
      message,
      trace_id: traceId,
    },
  };
}
