import { randomUUID } from 'node:crypto';

export type TenantStatus = 'ACTIVE' | 'SUSPENDED' | 'ARCHIVED';
export type MembershipStatus = 'ACTIVE' | 'INVITED' | 'SUSPENDED' | 'REMOVED';

export const TENANT_PERMISSIONS = [
  'tenant.read',
  'tenant.manage',
  'company.read',
  'company.update',
  'member.read',
  'member.invite',
  'member.manage',
  'member.remove',
  'role.read',
  'role.manage',
  'audit.read',
  'document.read',
  'document.upload',
  'document.manage',
  'accounting.read',
  'journal.create',
  'journal.post',
  'journal.reverse',
  'period.manage',
  'period.reopen',
  'chart.manage',
  'sales.read',
  'sales.customer.manage',
  'invoice.create',
  'invoice.issue',
  'invoice.credit',
  'invoice.pdf.retry',
  'sales.settings.manage',
  'purchase.read',
  'purchase.create',
  'purchase.edit',
  'purchase.review',
  'purchase.approve',
  'purchase.post',
  'purchase.reject',
  'purchase.correct',
  'supplier.manage',
  'purchase.settings.manage',
  'purchase.document.upload',
  'registry.read',
  'tax.read',
  'tax.manage',
  'tax.report.read',
  'purchase.classify',
  'purchase.classification.apply',
  'sales.payment.record',
  'sales.reminder.create',
  'sales.recurring.manage',
  'sales.invoice.send',
  'sales.einvoice.export',
  'banking.read',
  'banking.import',
  'banking.match',
  'banking.post',
  'banking.accounts.manage',
  'employees.read',
  'employees.create',
  'employees.update',
  'employees.manage_sensitive',
  'employees.terminate',
] as const;

export type TenantPermission = (typeof TENANT_PERMISSIONS)[number];

export interface BuiltinRoleDefinition {
  name: string;
  permissions: TenantPermission[];
}

export const BUILTIN_ROLES: BuiltinRoleDefinition[] = [
  {
    name: 'Owner',
    permissions: [...TENANT_PERMISSIONS],
  },
  {
    name: 'Admin',
    permissions: [
      'tenant.read',
      'company.read',
      'company.update',
      'member.read',
      'member.invite',
      'member.manage',
      'member.remove',
      'role.read',
      'role.manage',
      'audit.read',
      'document.read',
      'document.upload',
      'document.manage',
      'accounting.read',
      'journal.create',
      'journal.post',
      'journal.reverse',
      'period.manage',
      'period.reopen',
      'chart.manage',
      'sales.read',
      'sales.customer.manage',
      'invoice.create',
      'invoice.issue',
      'invoice.credit',
      'invoice.pdf.retry',
      'sales.settings.manage',
      'purchase.read',
      'purchase.create',
      'purchase.edit',
      'purchase.review',
      'purchase.approve',
      'purchase.post',
      'purchase.reject',
      'purchase.correct',
      'supplier.manage',
      'purchase.settings.manage',
      'purchase.document.upload',
      'registry.read',
      'tax.read',
      'tax.manage',
      'tax.report.read',
      'purchase.classify',
      'purchase.classification.apply',
      'sales.payment.record',
      'sales.reminder.create',
      'sales.recurring.manage',
      'sales.invoice.send',
      'sales.einvoice.export',
      'banking.read',
      'banking.import',
      'banking.match',
      'banking.post',
      'banking.accounts.manage',
      'employees.read',
      'employees.create',
      'employees.update',
      'employees.manage_sensitive',
      'employees.terminate',
    ],
  },
  {
    name: 'Accountant',
    permissions: [
      'tenant.read',
      'company.read',
      'member.read',
      'role.read',
      'audit.read',
      'document.read',
      'document.upload',
      'accounting.read',
      'journal.create',
      'journal.post',
      'sales.read',
      'sales.customer.manage',
      'invoice.create',
      'invoice.issue',
      'invoice.credit',
      'invoice.pdf.retry',
      'purchase.read',
      'purchase.create',
      'purchase.edit',
      'purchase.review',
      'purchase.approve',
      'purchase.post',
      'purchase.reject',
      'purchase.correct',
      'supplier.manage',
      'purchase.document.upload',
      'registry.read',
      'tax.read',
      'tax.report.read',
      'purchase.classify',
      'purchase.classification.apply',
      'sales.payment.record',
      'sales.reminder.create',
      'sales.recurring.manage',
      'sales.invoice.send',
      'sales.einvoice.export',
      'banking.read',
      'banking.import',
      'banking.match',
      'banking.post',
      'banking.accounts.manage',
      'employees.read',
      'employees.create',
      'employees.update',
      'employees.manage_sensitive',
      'employees.terminate',
    ],
  },
  {
    name: 'Employee',
    permissions: [
      'tenant.read',
      'company.read',
      'document.read',
      'sales.read',
      'purchase.read',
      'registry.read',
      'tax.read',
      'purchase.classify',
    ],
  },
  {
    name: 'Viewer',
    permissions: [
      'tenant.read',
      'company.read',
      'document.read',
      'sales.read',
      'purchase.read',
      'registry.read',
      'tax.read',
      'purchase.classify',
    ],
  },
];

export function generateTenantId(): string {
  return randomUUID();
}

export function isValidTenantSlug(slug: string): boolean {
  return /^[a-z0-9][a-z0-9-]{2,62}$/.test(slug);
}

export function normalizeTenantSlug(input: string): string {
  return input
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}
